#!/usr/bin/env bash
# Biblical Jurisprudence — Round 2 ingestion runner
#
# Reads court IDs from .court_ids_v2.txt (generated by seed_courts_v2.py)
# and runs ingest_v2.py for each court sequentially.
#
# Supports resuming: --skip N  skips the first N courts.
# Supports single-court testing: --court ca9
#
# Usage:
#   bash run_v2.sh                    # run all courts
#   bash run_v2.sh --skip 10          # resume from court #11
#   bash run_v2.sh --court scotus     # single court (ignores .court_ids_v2.txt)
#   bash run_v2.sh --after 1975-01-01 # override start date (default: 1975-01-01)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PYTHON="$SCRIPT_DIR/.venv/bin/python"
COURT_IDS_FILE="$SCRIPT_DIR/.court_ids_v2.txt"
LOG_DIR="$SCRIPT_DIR/logs"
AFTER="1975-01-01"
SKIP=0
SINGLE_COURT=""

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --skip)   SKIP="$2";         shift 2 ;;
        --after)  AFTER="$2";        shift 2 ;;
        --court)  SINGLE_COURT="$2"; shift 2 ;;
        *) echo "Unknown argument: $1"; exit 1 ;;
    esac
done

mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/run_v2_$(date +%Y%m%d_%H%M%S).log"

log() { echo "$1" | tee -a "$LOG_FILE"; }

log "============================================="
log "Biblical Jurisprudence — Round 2 Ingestion"
log "Started: $(date)"
log "After:   $AFTER"
log "============================================="

# Build court list
if [[ -n "$SINGLE_COURT" ]]; then
    COURTS=("$SINGLE_COURT")
    log "Single court mode: $SINGLE_COURT"
else
    if [[ ! -f "$COURT_IDS_FILE" ]]; then
        echo "Error: $COURT_IDS_FILE not found."
        echo "Run: python seed_courts_v2.py"
        exit 1
    fi
    mapfile -t ALL_COURTS < "$COURT_IDS_FILE" 2>/dev/null || {
        # macOS bash 3.2 fallback
        ALL_COURTS=()
        while IFS= read -r line; do
            [[ -n "$line" ]] && ALL_COURTS+=("$line")
        done < "$COURT_IDS_FILE"
    }
    COURTS=("${ALL_COURTS[@]:$SKIP}")
    TOTAL_ALL="${#ALL_COURTS[@]}"
    log "Total courts in file: $TOTAL_ALL"
    log "Skipping first $SKIP courts. Running ${#COURTS[@]} courts."
fi

TOTAL="${#COURTS[@]}"
DONE=0
FAILED=0
FAILED_COURTS=()

for court in "${COURTS[@]}"; do
    DONE=$((DONE + 1))
    OVERALL=$((SKIP + DONE))
    log ""
    log "[$DONE/$TOTAL] (overall #$OVERALL) Court: $court  —  $(date)"

    if "$PYTHON" "$SCRIPT_DIR/ingest_v2.py" \
        --court "$court" \
        --after "$AFTER" \
        2>&1 | tee -a "$LOG_FILE"; then
        log "[OK] $court"
    else
        log "[FAILED] $court"
        FAILED=$((FAILED + 1))
        FAILED_COURTS+=("$court")
    fi
done

log ""
log "============================================="
log "Completed: $(date)"
log "Courts processed: $DONE"
log "Failures: $FAILED"
if [[ ${#FAILED_COURTS[@]} -gt 0 ]]; then
    log "Failed courts: ${FAILED_COURTS[*]}"
fi
log "Log: $LOG_FILE"
log "============================================="

# Print resume command if any failures
if [[ $FAILED -gt 0 ]]; then
    echo ""
    echo "To retry failed courts individually:"
    for c in "${FAILED_COURTS[@]}"; do
        echo "  bash run_v2.sh --court $c --after $AFTER"
    done
fi
